-- Corrects a real defect found 2026-09-05, empirically, not by re-reading
-- the code: trailing_stop_triggered is FALSE for all 37 migrated rows in
-- trades_v2, not NULL as 003's own comment claimed ("left NULL by
-- omission"). That comment was wrong (fixed separately, in 003 itself).
-- 003's INSERT never lists trailing_stop_triggered in its column list --
-- but 002 declared the column `boolean default false`, and omitting a
-- column from an INSERT applies its DEFAULT, not NULL. The unknown/false
-- distinction this field exists to preserve was destroyed at migration
-- time, not just mis-read by the mapper (which has been fixed
-- separately, in the same pass that found this, to stop assuming
-- `!!row.trailing_stop_triggered` means "confirmed false").
--
-- Verified via direct query (not re-reading 002/003), same session:
--   select trailing_stop_triggered, count(*) from trades_v2 group by 1;
-- returned 37 rows, all `false`, zero `null` -- confirming the DEFAULT
-- fired for every one of them, not a mix that a spot-check might have
-- missed.
--
-- momentum_protection and catalyst_setup do NOT have this problem --
-- checked the same way, not assumed clean by analogy: both were
-- explicitly listed in 003's column list, both are copied from the old
-- `trades` table's real historical values (catalyst_setup: 5 true / 32
-- false, a genuine mix; momentum_protection: 37 false, confirmed to
-- match the SAME distribution already present in the old `trades` table
-- itself, i.e. real trading history, not a masked default). No fix
-- needed for either.
--
-- STEP 1: reset the already-migrated rows to the true unknown state.
-- DATE-BOUNDED (2026-09-05, added before running -- the first draft had
-- no guard at all beyond a comment saying "must not be re-run after new
-- trades exist," and a warning is not a mechanism, the same lesson
-- 003/005/006/007 already paid for). Every migrated row has a created_at
-- from before this migration ran; no trade written through the real
-- app after cutover ever will. Bounding by created_at means a second run
-- is harmless (it would just re-null the same already-null rows, since
-- no row created after the cutover date can ever match), rather than
-- silently wiping a real captured value on a new trade.
update trades_v2 set trailing_stop_triggered = null
where created_at < timestamptz '2026-09-05 00:00:00+00';

-- STEP 2: drop the column default so this can't happen again silently --
-- any future insert that forgets to specify this column will now get a
-- real NULL (correctly meaning "not captured"), not a false "confirmed
-- not triggered." writeTradeToSupabase already sets this column
-- explicitly on every new trade (app.js, trades_v2 cutover commit), so
-- this only guards against a future insert path that doesn't.
alter table trades_v2 alter column trailing_stop_triggered drop default;

-- RUN 2026-09-05. VERIFIED (not by status code -- by re-querying):
--   select trailing_stop_triggered, count(*) from trades_v2 group by 1;
-- returned 37 rows, all null, zero false.
