-- scan_runs: one row per logger run, recording what it ATTEMPTED versus
-- what it COMPLETED. Without this, a partial scan (Alpaca 429s partway
-- through, an aborted evaluateGateBatch) produces fewer signal_log rows
-- and looks identical to a day where fewer candidates existed -- this
-- project's signature failure mode, aimed directly at the dataset the
-- forward test depends on. Every rate computed over signal_log without
-- being able to exclude incomplete runs is not a measurement.
--
-- session IS NOT OPTIONAL, and this is enforced, not just documented:
-- RVOL is structurally not-checked for every candidate in a CLOSED or
-- early-PRE session (see engines/warrior/gate.js's rvolCheckable), which
-- means a CLOSED-session run's tier distribution is not comparable to an
-- OPEN-session run's -- pooling them silently would blend two different
-- populations into one number. signal_log.scan_session is the join key
-- that makes filtering by session possible at all; both columns are
-- NOT NULL below, and signal_log.scan_session gets a real foreign key,
-- so "which session produced this row" can never be lost or optional by
-- omission the way a documentation-only requirement eventually is.
create table if not exists scan_runs (
  id text primary key, -- matches signal_log.scan_session's existing text type; generated by the logger (crypto.randomUUID()), not a DB default
  engine_source text not null check (engine_source in ('EDGE', 'WARRIOR')),
  session text not null check (session in ('OPEN', 'PRE', 'AH', 'CLOSED')),
  scan_date date not null,
  started_at timestamptz not null,
  universe_source text not null check (universe_source in ('committed-movers-snapshot', 'self-fetched-fallback')),
  universe_snapshot_captured_at timestamptz,
  universe_count integer not null,
  evaluated_count integer not null,
  fetch_failed_count integer not null default 0,
  aborted boolean not null default false,
  abort_reason text,
  build_version text,
  created_at timestamptz not null default now()
);

create index if not exists scan_runs_engine_date_idx on scan_runs (engine_source, scan_date);

-- The FK signal_log has been missing since 001: scan_session was typed
-- `text` with no constraint tying it to anything, purely a join
-- convenience. Enforcing it now, while signal_log is still empty of any
-- real logger-written row (confirmed via a live select before drafting
-- this, not assumed) -- costs nothing today and guarantees every future
-- row's scan_session actually names a real run.
alter table signal_log alter column scan_session set not null;
alter table signal_log add constraint fk_signal_log_scan_session
  foreign key (scan_session) references scan_runs(id);

-- RLS: same fail-closed shape as signal_log -- anon insert+select only.
-- No update, no delete, for any role. A scan_runs row is written once,
-- at the end of a run, and never touched again.
alter table scan_runs enable row level security;

drop policy if exists "anon insert" on scan_runs;
create policy "anon insert" on scan_runs for insert to anon with check (true);

drop policy if exists "anon select" on scan_runs;
create policy "anon select" on scan_runs for select to anon using (true);

-- VERIFICATION PLAN (same shape as every other RLS pass this phase):
-- insert a disposable scan_runs row via the anon key, confirm it reads
-- back; confirm inserting a signal_log row with a scan_session that
-- does NOT match any scan_runs.id is rejected by the new FK (not
-- silently accepted); attempt an UPDATE and a DELETE on the dummy
-- scan_runs row -- expect both blocked, confirmed by re-select, not
-- status code.
